# fly.toml app configuration file generated for hammer-partner-rs on 2023-11-20T03:04:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hammer-partner-rs"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
